import { config } from '../config.js';

export async function generateGeminiReply(prompt: string, contextSummary?: string) {
  if (!config.geminiApiKey) {
    return 'Gemini is not configured. Add GEMINI_API_KEY to your environment and restart the API.';
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${config.geminiModel}:generateContent?key=${config.geminiApiKey}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `You are TOMI AI, a helpful personal assistant. Reply naturally in Bangla or English. Respond concisely by default and become detailed when needed. \n\nContext summary:\n${contextSummary ?? 'No prior context available.'}\n\nUser request:\n${prompt}`,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topP: 0.9,
          maxOutputTokens: 600,
        },
      }),
    },
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Gemini request failed: ${errorText}`);
  }

  const data = (await response.json()) as any;
  const parts = data?.candidates?.[0]?.content?.parts ?? [];
  const extractedText = parts.map((part: any) => part.text ?? '').join('\n');

  return extractedText || 'No response generated by Gemini.';
}
